<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Accessions Report</title>
    <style>
        @page {
            size: A4 landscape;
            margin: 15mm 10mm 15mm 10mm;
        }

        body { font-family: sans-serif; font-size: 9px; color: #333; margin: 0; padding: 0; }

        .header { display: table; width: 100%; margin-bottom: 10px; border-bottom: 2px solid #cbd5e1; padding-bottom: 6px; }
        .header-left { display: table-cell; vertical-align: middle; width: 45px; }
        .header-left img { width: 40px; height: 40px; object-fit: contain; }
        .header-center { display: table-cell; vertical-align: middle; }
        .header-center h2 { margin: 0; font-size: 14px; color: #1e293b; text-transform: uppercase; }
        .header-center p { margin: 1px 0 0; color: #64748b; font-size: 8.5px; }

        .meta { margin-bottom: 10px; font-size: 8.5px; background-color: #f8fafc; padding: 6px 10px; border: 1px solid #e2e8f0; border-radius: 4px; }
        .meta table { width: 100%; margin: 0; border: none; }
        .meta td { border: none; padding: 1px 0; width: 50%; color: #334155; }
        .meta td strong { color: #0f172a; }

        table.data-table { width: 100%; border-collapse: collapse; margin-top: 5px; table-layout: fixed; }
        th, td { border: 1px solid #cbd5e1; padding: 4px 5px; text-align: left; word-wrap: break-word; font-size: 8px; }
        th { background-color: #f1f5f9; font-weight: bold; font-size: 8px; color: #475569; text-transform: uppercase; }
        tr:nth-child(even) { background-color: #f8fafc; }

        .text-center { text-align: center; }
    </style>
</head>
<body>

    <div class="header">
        <div class="header-left">
            <img src="{{ public_path('images/bps-logo.png') }}" alt="Logo">
        </div>
        <div class="header-center">
            <h2>BPS Library Management System</h2>
            <p>Accessions Report</p>
        </div>
    </div>

    <div class="meta">
        <table>
            <tr>
                <td><strong>Generated On:</strong> {{ $date }}</td>
                <td><strong>Generated By:</strong> {{ auth()->user()->getFullNameAttribute() ?? 'System' }}</td>
            </tr>
            <tr>
                <td><strong>Total Records:</strong> {{ count($accessions) }}</td>
                <td><strong>Role:</strong> {{ ucfirst(auth()->user()->role ?? 'Administrator') }}</td>
            </tr>
            <tr>
                <td><strong>Search Filter:</strong> {{ !empty($filters['search']) ? $filters['search'] : 'All (None applied)' }}</td>
                <td><strong>Status Filter:</strong> {{ !empty($filters['status']) ? ucfirst($filters['status']) : 'All Statuses' }}</td>
            </tr>
        </table>
    </div>

    <table class="data-table">
        <thead>
            <tr>
                <th style="width: 9%;">Accession #</th>
                <th style="width: 8%;">Batch #</th>
                <th style="width: 9%;">Acquisition #</th>
                <th style="width: 18%;">Catalog Title</th>
                <th style="width: 12%;">Author</th>
                <th style="width: 11%;">Publisher</th>
                <th style="width: 7%;" class="text-center">Gen. Ref</th>
                <th style="width: 8%;">Asset Type</th>
                <th style="width: 8%;" class="text-center">Call Number</th>
                <th style="width: 5%;" class="text-center">Condition</th>
                <th style="width: 5%;" class="text-center">Status</th>
            </tr>
        </thead>
        <tbody>
            @forelse($accessions as $item)
                <tr>
                    <td><strong>{{ $item->accession_number }}</strong></td>
                    <td>{{ $item->batch_number }}</td>
                    <td>{{ $item->acquisition->acquisition_number }}</td>
                    <td>{{ ucwords($item->catalog->title) }}</td>
                    <td>{{ ucwords($item->catalog->author->name) }}</td>
                    <td>{{ ucwords($item->catalog->publisher->name) }}</td>
                    <td class="text-center">{{ ucwords($item->catalog->generalReference->name) }}</td>
                    <td>{{ ucwords($item->catalog->assetType->name) }}</td>
                    <td class="text-center">{{ strtoupper($item->call_number) }}</td>
                    <td class="text-center">{{ ucfirst($item->condition) }}</td>
                    <td class="text-center">{{ ucfirst($item->status) }}</td>
                </tr>
            @empty
                <tr>
                    <td colspan="11" style="text-align: center; color: #94a3b8; padding: 12px;">
                        No accession records found matching the selected criteria.
                    </td>
                </tr>
            @endforelse
        </tbody>
    </table>

</body>
</html>
