<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Accessions Report</title>
    <style>
        @page {
            size: A4 landscape;
            margin: 10mm;
        }

        body { font-family: DejaVu Sans, sans-serif; font-size: 8px; color: #1f2937; margin: 0; padding: 0; }

        .header-container { border-bottom: 2px solid #1e3a8a; padding-bottom: 6px; margin-bottom: 8px; }
        .system-title { font-size: 13px; font-weight: bold; color: #1e3a8a; text-transform: uppercase; margin: 0 0 2px 0; }
        .report-title { font-size: 10px; font-weight: bold; color: #4b5563; margin: 0; }

        .meta-box { border: 1px solid #e5e7eb; background-color: #f9fafb; padding: 6px 8px; margin-bottom: 8px; font-size: 8px; }
        .meta-table { width: 100%; border-collapse: collapse; border: none; }
        .meta-table td { border: none; padding: 1.5px 0; color: #4b5563; width: 50%; }
        .meta-table td strong { color: #1f2937; }

        table.data-table { width: 100%; border-collapse: collapse; table-layout: fixed; }
        table.data-table th, table.data-table td { border: 1px solid #d1d5db; padding: 3px 4px; text-align: left; vertical-align: middle; word-wrap: break-word; }
        table.data-table th { background-color: #1e3a8a; color: #ffffff; font-weight: bold; text-transform: uppercase; font-size: 7px; }

        .text-center { text-align: center; }
        tr:nth-child(even) { background-color: #f9fafb; }
    </style>
</head>
<body>
    <div class="header-container">
        <h1 class="system-title">BPS Library Management System</h1>
        <div class="report-title">Accessions Report</div>
    </div>

    <div class="meta-box">
        <table class="meta-table">
            <tr>
                <td><strong>Generated On:</strong> {{ $date }}</td>
                <td><strong>Generated By:</strong> {{ auth()->user()->getFullNameAttribute() ?? 'System' }}</td>
            </tr>
            <tr>
                <td><strong>Total Records:</strong> {{ count($accessions) }}</td>
                <td><strong>Role:</strong> {{ ucfirst(auth()->user()->role ?? 'Administrator') }}</td>
            </tr>
            <tr>
                <td><strong>Search Filter:</strong> {{ !empty($filters['search']) ? $filters['search'] : 'All (None applied)' }}</td>
                <td><strong>Status Filter:</strong> {{ !empty($filters['status']) ? ucfirst($filters['status']) : 'All Statuses' }}</td>
            </tr>
        </table>
    </div>

    <table class="data-table">
        <thead>
            <tr>
                <th style="width: 9%;">Accession #</th>
                <th style="width: 10%;">Batch #</th>
                <th style="width: 9%;">Acquisition #</th>
                <th style="width: 14%;">ISBN/ISSN</th>
                <th style="width: 14%;">Title</th>
                <th style="width: 9%;">Author</th>
                <th style="width: 10%;">Publisher</th>
                <th style="width: 8%;" class="text-center">Gen. Ref</th>
                <th style="width: 7%;" class="text-center">Asset Type</th>
                <th style="width: 8%;" class="text-center">Copyright Year</th>
                <th style="width: 8%;" class="text-center">Call Number</th>
                <th style="width: 8%;" class="text-center">Condition</th>
                <th style="width: 8%;" class="text-center">Status</th>
            </tr>
        </thead>
        <tbody>
            @forelse($accessions as $item)
                <tr>
                    <td><strong>{{ strtoupper($item->accession_number) }}</strong></td>
                    <td>{{ strtoupper($item->batch_number) }}</td>
                    <td>{{ strtoupper($item->acquisition->acquisition_number ?? '—') }}</td>
                    <td>{{ $item->catalog->isbn_issn ?? 'N/A' }}</td>
                    <td>{{ ucwords($item->catalog->title ?? 'N/A') }}</td>
                    <td>{{ ucwords($item->catalog->author->name ?? 'N/A') }}</td>
                    <td>{{ ucwords($item->catalog->publisher->name ?? 'N/A') }}</td>
                    <td class="text-center">{{ ucwords($item->catalog->generalReference->name ?? 'N/A') }}</td>
                    <td class="text-center">{{ ucwords($item->catalog->assetType->name ?? 'N/A') }}</td>
                    <td class="text-center">{{ $item->catalog->copyright_year ?? 'N/A' }}</td>
                    <td class="text-center">{{ strtoupper($item->call_number ?? 'N/A') }}</td>
                    <td class="text-center">{{ ucfirst($item->condition ?? 'N/A') }}</td>
                    <td class="text-center">{{ ucfirst($item->status ?? 'N/A') }}</td>
                </tr>
            @empty
                <tr>
                    <td colspan="11" class="text-center" style="color: #94a3b8; padding: 12px;">
                        No accession records found matching the selected criteria.
                    </td>
                </tr>
            @endforelse
        </tbody>
    </table>
</body>
</html>
