<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Acquisitions Report</title>
    <style>
        body { font-family: DejaVu Sans, sans-serif; font-size: 9px; color: #1f2937; margin: 0; padding: 0; }
        .header-container { border-bottom: 2px solid #1e3a8a; padding-bottom: 8px; margin-bottom: 12px; }
        .system-title { font-size: 14px; font-weight: bold; color: #1e3a8a; text-transform: uppercase; margin: 0 0 2px 0; }
        .report-title { font-size: 11px; font-weight: bold; color: #4b5563; margin: 0; }

        .meta-box { border: 1px solid #e5e7eb; background-color: #f9fafb; padding: 8px 10px; margin-bottom: 12px; font-size: 8.5px; }
        .meta-table { width: 100%; border-collapse: collapse; border: none; }
        .meta-table td { border: none; padding: 2px 0; color: #4b5563; }

        table.data-table { width: 100%; border-collapse: collapse; table-layout: fixed; }
        table.data-table th, table.data-table td { border: 1px solid #d1d5db; padding: 4px 5px; text-align: left; vertical-align: top; word-wrap: break-word; }
        table.data-table th { background-color: #1e3a8a; color: #ffffff; font-weight: bold; text-transform: uppercase; font-size: 7.5px; }

        .text-right { text-align: right; }
        .text-center { text-align: center; }
        tfoot td { font-weight: bold; background-color: #f3f4f6; color: #1f2937; }
    </style>
</head>
<body>
    <div class="header-container">
        <h1 class="system-title">BPS Library Management System</h1>
        <div class="report-title">Acquisitions Report</div>
    </div>

    <div class="meta-box">
        <table class="meta-table">
            <tr>
                <td><strong>Generated On:</strong> {{ $date->format('F d, Y h:i A') }}</td>
                <td><strong>Total Records:</strong> {{ $acquisitions->count() }}</td>
            </tr>
            <tr>
                <td><strong>Search Filter:</strong> {{ !empty($searchTerm) ? '"' . $searchTerm . '"' : 'None (All applied)' }}</td>
                <td><strong>Generated By:</strong> {{ auth()->user()->getFullNameAttribute() ?? 'System' }}</td>
            </tr>
            <tr>
                <td colspan="1"></td>
                <td colspan="1"><strong>Role:</strong> {{ ucwords(auth()->user()->role) ?? 'Librarian' }}</td>
            </tr>
        </table>
    </div>

    <table class="data-table">
        <thead>
            <tr>
                <th style="width: 8%;">ACQ #</th>
                <th style="width: 8%;">Txn #</th>
                <th style="width: 8%;">Delivery Type</th>
                <th style="width: 13%;">Title</th>
                <th style="width: 10%;">Author</th>
                <th style="width: 9%;">Asset Type</th>
                <th style="width: 10%;">Vendor</th>
                <th style="width: 4%;" class="text-center">Qty</th>
                <th style="width: 8%;" class="text-right">Unit Cost</th>
                <th style="width: 9%;" class="text-right">Total Cost</th>
                <th style="width: 10%;">Received</th>
                <th style="width: 11%;">Remarks</th>
            </tr>
        </thead>
        <tbody>
            @forelse($acquisitions as $acq)
                <tr>
                    <td>{{ strtoupper($acq->acquisition_number) }}</td>
                    <td>{{ strtoupper($acq->transaction_number) }}</td>
                    <td>{{ ucwords($acq->delivery_type) }}</td>
                    <td>{{ ucwords($acq->catalog->title ?? 'N/A') }}</td>
                    <td>{{ ucwords($acq->catalog->author->name ?? 'N/A') }}</td>
                    <td>{{ ucwords($acq->catalog->assetType->name ?? 'N/A') }}</td>
                    <td>{{ ucwords($acq->vendor->company_name ?? 'N/A') }}</td>
                    <td class="text-center">{{ $acq->quantity }}</td>
                    <td class="text-right">{{ number_format($acq->unit_cost, 2) }}</td>
                    <td class="text-right">{{ number_format($acq->total_cost, 2) }}</td>
                    <td>{{ $acq->received_date ? $acq->received_date->format('M d, Y') : '—' }}</td>
                    <td>{{ ucfirst($acq->remarks) ?? '—' }}</td>
                </tr>
            @empty
                <tr>
                    <td colspan="11" class="text-center">No records found.</td>
                </tr>
            @endforelse
        </tbody>
        @if($acquisitions->count() > 0)
            <tfoot>
                <tr>
                    <td colspan="8" class="text-right">Grand Total:</td>
                    <td class="text-right">{{ number_format($acquisitions->sum('total_cost'), 2) }}</td>
                    <td colspan="2"></td>
                </tr>
            </tfoot>
        @endif
    </table>
</body>
</html>
