<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Borrower Attendance Logs Report</title>
    <style>
        body {
            font-family: sans-serif;
            font-size: 11px;
            color: #333;
            margin: 0;
            padding: 0;
        }
        .system-header {
            width: 100%;
            border-bottom: 2px solid #1e293b;
            padding-bottom: 12px;
            margin-bottom: 15px;
        }
        .logo-cell {
            width: 70px;
            vertical-align: middle;
        }
        .logo-img {
            max-width: 60px;
            max-height: 60px;
            object-fit: contain;
        }
        .header-title-cell {
            vertical-align: middle;
            text-align: left;
        }
        .system-name {
            font-size: 18px;
            font-weight: bold;
            color: #0f172a;
            margin: 0;
            text-transform: uppercase;
            letter-spacing: 0.5px;
        }
        .report-subtitle {
            font-size: 12px;
            font-weight: bold;
            color: #475569;
            margin: 2px 0 0 0;
        }
        .meta-box {
            background-color: #f8fafc;
            border: 1px solid #e2e8f0;
            border-radius: 4px;
            padding: 8px 12px;
            margin-bottom: 15px;
            font-size: 10px;
            color: #334155;
        }
        .meta-table {
            width: 100%;
            border: none !important;
            margin: 0 !important;
        }
        .meta-table td {
            border: none !important;
            padding: 2px 0 !important;
            background: transparent !important;
        }
        .filter-badge {
            font-weight: bold;
            color: #2563eb;
        }
        table.data-table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 10px;
        }
        table.data-table th, table.data-table td {
            border: 1px solid #cbd5e1;
            padding: 6px 8px;
            text-align: left;
        }
        table.data-table th {
            background-color: #f1f5f9;
            font-weight: bold;
            text-transform: uppercase;
            font-size: 9px;
            color: #475569;
        }
        table.data-table tr:nth-child(even) {
            background-color: #f8fafc;
            }
        .badge {
            padding: 2px 6px;
            border-radius: 3px;
            font-size: 9px;
            font-weight: bold;
        }
        .badge-green {
            background-color: #dcfce7;
            color: #15803d;
        }
        .badge-blue {
            background-color: #dbeafe;
            color: #1e40af;
        }
    </style>
</head>
<body>

    <!-- SYSTEM LOGO & HEADER -->
    <table class="system-header">
        <tr>
            <td class="logo-cell">
                <!-- If using a local public image path, DomPDF uses public_path() -->
                @if(file_exists(public_path('images/bps-logo.png')))
                    <img src="{{ public_path('images/bps-logo.png') }}" class="logo-img" alt="System Logo">
                @else
                    <div style="font-weight: bold; font-size: 20px; color: #1e293b;">[LOGO]</div>
                @endif
            </td>
            <td class="header-title-cell">
                <h1 class="system-name">{{ config('app.name', 'Library Management System') }}</h1>
                <p class="report-subtitle">Borrower Attendance Logs Report</p>
            </td>
        </tr>
    </table>

    <!-- METADATA & FILTERS INFO -->
    <div class="meta-box">
        <table class="meta-table">
            <tr>
                <td style="width: 50%;">
                    <strong>Generated By:</strong>
                    {{ auth()->check() ? auth()->user()->getFullNameAttribute() : 'System Administrator' }}
                    ({{ auth()->check() ? (auth()->user()->role ?? 'Staff') : 'Admin' }})
                </td>
                <td style="width: 50%; text-align: right;">
                    <strong>Date Generated:</strong> {{ now()->format('M d, Y h:i A') }}
                </td>
            </tr>
            <tr>
                <td style="width: 50%;">
                    <strong>Date Filter:</strong>
                    <span class="filter-badge">
                        {{ (! empty($filterDate) && $filterDate !== 'All Dates') ? \Carbon\Carbon::parse($filterDate)->format('M d, Y') : 'All Dates (Unfiltered)' }}
                    </span>
                </td>
                <td style="width: 50%; text-align: right;">
                    <strong>Status Filter:</strong> {{ ucfirst(str_replace('_', ' ', $filterStatus ?? 'all')) }}
                </td>
            </tr>
            <tr>
                <td style="width: 50%;">
                    <strong>Search Term:</strong> {{ ! empty($search) ? '"'.$search.'"' : 'None' }}
                </td>
                <td style="width: 50%; text-align: right;">
                    <strong>Total Records Found:</strong> {{ count($logs) }}
                </td>
            </tr>
        </table>
    </div>

    <!-- MAIN LOGS TABLE -->
    <table class="data-table">
        <thead>
            <tr>
                <th>#</th>
                <th>Date</th>
                <th>Student/Employee #</th>
                <th>Name</th>
                <th>Type</th>
                <th>Grade & Section</th>
                <th>Time In</th>
                <th>Time Out</th>
                <th>Status</th>
            </tr>
        </thead>
        <tbody>
            @forelse($logs as $index => $log)
                <tr>
                    <td>{{ $index + 1 }}</td>
                    <td>{{ \Carbon\Carbon::parse($log->log_date)->format('M d, Y') }}</td>
                    <td>{{ $log->patron->school_id ?? 'N/A' }}</td>
                    <td>
                        @if($log->patron)
                            {{ ucwords($log->patron->first_name ?? '') }}
                            {{ ucwords($log->patron->middle_name ?? '') }}
                            {{ ucwords($log->patron->last_name ?? '') }}
                            {{ blank($log->patron->suffix) ? '' : ' ' . ucwords($log->patron->suffix) }}
                        @else
                            Deleted Borrower
                        @endif
                    </td>
                    <td>{{ ucwords($log->patron->patronType->name ?? 'N/A') }}</td>
                    <td>
                        @if(optional($log->patron)->gradeLevel)
                            {{ ucwords($log->patron->gradeLevel->name) }}
                            {{ optional($log->patron->section)->name ? ' - ' . ucwords($log->patron->section->name) : '' }}
                        @else
                            N/A
                        @endif
                    </td>
                    <td>{{ $log->time_in ? \Carbon\Carbon::parse($log->time_in)->format('h:i:s A') : '--:--:--' }}</td>
                    <td>{{ $log->time_out ? \Carbon\Carbon::parse($log->time_out)->format('h:i:s A') : '--:--:--' }}</td>
                    <td>
                        @if($log->time_out)
                            <span class="badge badge-blue">Logged Out</span>
                        @else
                            <span class="badge badge-green">Inside Library</span>
                        @endif
                    </td>
                </tr>
            @empty
                <tr>
                    <td colspan="9" style="text-align: center; color: #999;">No attendance records found for this query.</td>
                </tr>
            @endforelse
        </tbody>
    </table>

</body>
</html>
