<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Borrower Attendance Logs Report</title>
    <style>
        body {
            font-family: sans-serif;
            font-size: 10px;
            color: #333;
            margin: 0;
            padding: 0;
        }
        .system-header {
            width: 100%;
            border-bottom: 2px solid #1e3a8a;
            padding-bottom: 8px;
            margin-bottom: 12px;
        }
        .system-name {
            font-size: 15px;
            font-weight: bold;
            color: #1e3a8a;
            margin: 0;
            text-transform: uppercase;
            letter-spacing: 0.3px;
        }
        .report-subtitle {
            font-size: 11px;
            font-weight: bold;
            color: #475569;
            margin: 2px 0 0 0;
        }
        .meta-box {
            background-color: #f8fafc;
            border: 1px solid #cbd5e1;
            border-radius: 2px;
            padding: 8px 10px;
            margin-bottom: 12px;
            font-size: 9.5px;
            color: #334155;
        }
        .meta-table {
            width: 100%;
            border: none !important;
            margin: 0 !important;
        }
        .meta-table td {
            border: none !important;
            padding: 2px 0 !important;
            background: transparent !important;
        }
        .filter-badge {
            font-weight: bold;
            color: #1e3a8a;
        }
        table.data-table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 5px;
        }
        table.data-table th, table.data-table td {
            border: 1px solid #cbd5e1;
            padding: 5px 6px;
            text-align: left;
        }
        table.data-table th {
            background-color: #1e3a8a;
            font-weight: bold;
            text-transform: uppercase;
            font-size: 8px;
            color: #ffffff;
            letter-spacing: 0.3px;
        }
        table.data-table tr:nth-child(even) {
            background-color: #f8fafc;
        }
        .badge {
            padding: 2px 5px;
            border-radius: 3px;
            font-size: 8px;
            font-weight: bold;
        }
        .badge-green {
            background-color: #dcfce7;
            color: #15803d;
        }
        .badge-blue {
            background-color: #dbeafe;
            color: #1e40af;
        }
    </style>
</head>
<body>

    <!-- SYSTEM HEADER -->
    <div class="system-header">
        <h1 class="system-name">{{ config('app.name', 'BPS Library Management System') }}</h1>
        <p class="report-subtitle">Borrower Attendance Logs Report</p>
    </div>

    <!-- METADATA & FILTERS INFO -->
    <div class="meta-box">
        <table class="meta-table">
            <tr>
                <td style="width: 50%;">
                    <strong>Generated On:</strong> {{ now()->format('F d, Y h:i A') }}
                </td>
                <td style="width: 50%;">
                    <strong>Total Records:</strong> {{ count($logs) }}
                </td>
            </tr>
            <tr>
                <td>
                    <strong>Search Filter:</strong> {{ !empty($search) ? '"'.$search.'"' : 'None (All applied)' }}
                </td>
                <td>
                    <strong>Generated By:</strong> {{ auth()->check() ? auth()->user()->getFullNameAttribute() : 'System Administrator' }}
                </td>
            </tr>
            <tr>
                <td>
                    <strong>Date Filter:</strong>
                    <span class="filter-badge">
                        {{ (!empty($filterDate) && $filterDate !== 'All Dates') ? \Carbon\Carbon::parse($filterDate)->format('M d, Y') : 'All Dates' }}
                    </span>
                </td>
                <td>
                    <strong>Role:</strong> {{ auth()->check() ? (ucwords(auth()->user()->role) ?? 'Librarian') : 'Admin' }}
                </td>
            </tr>
        </table>
    </div>

    <!-- MAIN LOGS TABLE -->
    <table class="data-table">
        <thead>
            <tr>
                <th>Log Date</th>
                <th>Student/Employee #</th>
                <th>Name</th>
                <th>Type</th>
                <th>Grade</th>
                <th>Section</th>
                <th>Log In Time</th>
                <th>Log Out Time</th>
                <th>Status</th>
            </tr>
        </thead>
        <tbody>
            @forelse($logs as $log)
                <tr>
                    <td>{{ \Carbon\Carbon::parse($log->log_date)->format('M d, Y') }}</td>
                    <td>{{ $log->patron->school_id ?? 'N/A' }}</td>
                    <td>
                        @if($log->patron)
                            {{ ucwords($log->patron->first_name ?? '') }}
                            {{ ucwords($log->patron->middle_name ?? '') }}
                            {{ ucwords($log->patron->last_name ?? '') }}
                            {{ blank($log->patron->suffix) ? '' : ' ' . strtoupper($log->patron->suffix) }}
                        @else
                            Deleted Borrower
                        @endif
                    </td>
                    <td>{{ ucwords($log->patron->patronType->name ?? 'N/A') }}</td>
                    <td>{{ optional(optional($log->patron)->gradeLevel)->name ? ucwords($log->patron->gradeLevel->name) : 'N/A' }}</td>
                    <td>{{ optional(optional($log->patron)->section)->name ? ucwords($log->patron->section->name) : 'N/A' }}</td>
                    <td>{{ $log->time_in ? \Carbon\Carbon::parse($log->time_in)->format('h:i:s A') : '--:--:--' }}</td>
                    <td>{{ $log->time_out ? \Carbon\Carbon::parse($log->time_out)->format('h:i:s A') : '--:--:--' }}</td>
                    <td>
                        @if($log->time_out)
                            <span class="badge badge-blue">Logged Out</span>
                        @else
                            <span class="badge badge-green">Inside Library</span>
                        @endif
                    </td>
                </tr>
            @empty
                <tr>
                    <td colspan="9" style="text-align: center; color: #999;">No attendance records found for this query.</td>
                </tr>
            @endforelse
        </tbody>
    </table>

</body>
</html>
