<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Circulation Report</title>
    <style>
        @page {
            margin: 20px;
        }
        body {
            font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif;
            font-size: 8px;
            color: #334155;
            margin: 0;
            padding: 0;
        }

        /* Top Branding Header */
        .header-table {
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 12px;
        }
        .header-table td {
            padding: 0;
            border: none;
            vertical-align: middle;
        }
        .brand-logo {
            width: 45px;
            height: 45px;
        }
        .brand-title {
            font-size: 14px;
            font-weight: 800;
            color: #0f172a;
            text-transform: uppercase;
            letter-spacing: 0.5px;
            margin: 0;
            line-height: 1.1;
        }
        .brand-subtitle {
            font-size: 8px;
            color: #64748b;
            margin-top: 2px;
        }

        /* Meta Information Card Panel */
        .meta-card {
            background-color: #f8fafc;
            border: 1px solid #e2e8f0;
            border-radius: 4px;
            padding: 8px 12px;
            margin-bottom: 12px;
        }
        .meta-table {
            width: 100%;
            border-collapse: collapse;
        }
        .meta-table td {
            padding: 2px 0;
            border: none;
            font-size: 7.5px;
            color: #475569;
            vertical-align: top;
        }
        .meta-label {
            font-weight: bold;
            color: #1e293b;
        }

        /* Main Data Table */
        table.data-table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 5px;
        }
        table.data-table th {
            background-color: #f1f5f9;
            color: #334155;
            text-align: left;
            padding: 6px 5px;
            font-size: 7px;
            font-weight: 700;
            text-transform: uppercase;
            border: 1px solid #cbd5e1;
            letter-spacing: 0.2px;
        }
        table.data-table td {
            padding: 5px;
            border: 1px solid #e2e8f0;
            font-size: 7.5px;
            color: #334155;
            vertical-align: middle;
        }
        table.data-table tr:nth-child(even) {
            background-color: #f8fafc;
        }

        /* Badges */
        .badge {
            display: inline-block;
            padding: 1px 4px;
            font-size: 6.5px;
            font-weight: 700;
            text-transform: uppercase;
            border-radius: 2px;
            text-align: center;
        }
        .badge-borrowed { background-color: #e0e7ff; color: #3730a3; }
        .badge-returned { background-color: #d1fae5; color: #065f46; }
        .badge-overdue { background-color: #ffe4e6; color: #9f1239; }
        .badge-default { background-color: #f1f5f9; color: #334155; }

        .badge-cond-good { background-color: #ecfdf5; color: #047857; }
        .badge-cond-damaged { background-color: #fffbeb; color: #b45309; }
        .badge-cond-lost { background-color: #fff1f2; color: #be123c; }

        /* Empty State */
        .empty-cell {
            text-align: center;
            color: #94a3b8;
            padding: 15px !important;
            font-style: italic;
        }
    </style>
</head>
<body>

    <!-- Header Section with Logo and Title -->
    <table class="header-table">
        <tr>
            <td style="width: 55px;">
                <img src="{{ public_path('images/bps-logo.png') }}" class="brand-logo" alt="System Logo">
            </td>
            <td>
                <div class="brand-title">BPS Library Management System</div>
                <div class="brand-subtitle">Circulation Report</div>
            </td>
        </tr>
    </table>

    <!-- Meta Information Grid -->
    <div class="meta-card">
        <table class="meta-table">
            <tr>
                <td style="width: 50%;">
                    <span class="meta-label">Generated On:</span> {{ now()->format('F d, Y g:i A') }}<br>
                    <span class="meta-label">Total Records:</span> {{ count($activeLoans) }}<br>
                    <span class="meta-label">Search Filter:</span> {{ $search ?? 'All (None applied)' }}
                </td>
                <td style="width: 50%;">
                    <span class="meta-label">Generated By:</span> {{ auth()->user()?->getFullNameAttribute() ?? 'System Administrator' }}<br>
                    <span class="meta-label">Role:</span> {{ auth()->user()?->role ? ucwords(auth()->user()->role) : 'Librarian' }}<br>
                    <span class="meta-label">Status Filter:</span> {{ ucfirst($filterStatus ?? 'All Statuses') }}
                </td>
            </tr>
        </table>
    </div>

    <!-- Data Table -->
    <table class="data-table">
        <thead>
            <tr>
                <th style="width: 8%;">Accession #</th>
                <th style="width: 16%;">Book Title</th>
                <th style="width: 9%;">Student/Emp #</th>
                <th style="width: 13%;">Borrower Name</th>
                <th style="width: 10%;">Borrowed At</th>
                <th style="width: 8%;">Due At</th>
                <th style="width: 8%;">Receipt #</th>
                <th style="width: 7%;">Fine Amount</th>
                <th style="width: 7%;">Condition</th>
                <th style="width: 6%;">Status</th>
                <th style="width: 8%;">Processed By</th>
            </tr>
        </thead>
        <tbody>
            @forelse ($activeLoans as $loan)
                @php
                    $cond = strtolower($loan->condition ?? 'good');
                    $condBadge = match($cond) {
                        'good' => 'badge-cond-good',
                        'damaged' => 'badge-cond-damaged',
                        'lost' => 'badge-cond-lost',
                        default => 'badge-default',
                    };

                    $status = strtolower($loan->status ?? '');
                    $statusBadge = match($status) {
                        'borrowed' => 'badge-borrowed',
                        'returned' => 'badge-returned',
                        'overdue' => 'badge-overdue',
                        default => 'badge-default',
                    };

                    $borrowerName = trim(implode(' ', array_filter([
                        $loan->patron?->first_name,
                        $loan->patron?->middle_name,
                        $loan->patron?->last_name,
                        $loan->patron?->suffix,
                    ])));

                    $processedBy = method_exists($loan->user, 'getFullNameAttribute')
                        ? $loan->user?->getFullNameAttribute()
                        : ($loan->user?->name ?? 'System User');
                @endphp
                <tr>
                    <td><strong>{{ $loan->accession?->accession_number ?? 'N/A' }}</strong></td>
                    <td>{{ $loan->accession?->catalog?->title ? ucwords(strtolower($loan->accession->catalog->title)) : 'N/A' }}</td>
                    <td>{{ $loan->patron?->school_id ?? 'N/A' }}</td>
                    <td>{{ $borrowerName ? ucwords(strtolower($borrowerName)) : 'N/A' }}</td>
                    <td>{{ $loan->borrowed_at?->format('M d, Y h:i A') ?? '-' }}</td>
                    <td>{{ $loan->due_at?->format('M d, Y') ?? '-' }}</td>
                    <td>{{ $loan->receipt_number ?? '-' }}</td>
                    <td>{{ number_format((float) ($loan->fine_amount ?? 0), 2) }}</td>
                    <td>
                        <span class="badge {{ $condBadge }}">{{ ucwords($loan->condition ?? 'Good') }}</span>
                    </td>
                    <td>
                        <span class="badge {{ $statusBadge }}">{{ ucwords($loan->status ?? 'N/A') }}</span>
                    </td>
                    <td>
                        {{ ucwords(strtolower($loan->user?->getFullNameAttribute() ?? 'System User')) }}
                    </td>
                </tr>
            @empty
                <tr>
                    <td colspan="11" class="empty-cell">
                        No circulation records found matching criteria.
                    </td>
                </tr>
            @endforelse
        </tbody>
    </table>

</body>
</html>
