<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Circulation Report</title>
    <style>
        @page {
            margin: 20px;
        }
        body {
            font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif;
            font-size: 8px;
            color: #334155;
            margin: 0;
            padding: 0;
        }

        /* Top Branding Header Style matching Acquisitions Report */
        .brand-title {
            font-size: 13px;
            font-weight: 700;
            color: #1e3a8a;
            text-transform: uppercase;
            letter-spacing: 0.3px;
            margin: 0;
            line-height: 1.1;
        }
        .brand-subtitle {
            font-size: 9px;
            font-weight: 600;
            color: #334155;
            margin-top: 3px;
            margin-bottom: 8px;
        }
        .header-divider {
            width: 100%;
            height: 2px;
            background-color: #1e3a8a;
            border: none;
            margin-bottom: 10px;
        }

        /* Meta Information Card Panel */
        .meta-card {
            background-color: #f8fafc;
            border: 1px solid #e2e8f0;
            border-radius: 2px;
            padding: 8px 10px;
            margin-bottom: 10px;
        }
        .meta-table {
            width: 100%;
            border-collapse: collapse;
        }
        .meta-table td {
            padding: 2px 0;
            border: none;
            font-size: 7.5px;
            color: #475569;
            vertical-align: top;
        }
        .meta-label {
            color: #1e293b;
        }

        /* Main Data Table */
        table.data-table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 5px;
        }
        table.data-table th {
            background-color: #1e3a8a;
            color: #ffffff;
            text-align: left;
            padding: 6px 4px;
            font-size: 6.5px;
            font-weight: 700;
            text-transform: uppercase;
            border: 1px solid #1e3a8a;
            letter-spacing: 0.2px;
        }
        table.data-table td {
            padding: 4px;
            border: 1px solid #e2e8f0;
            font-size: 7px;
            color: #334155;
            vertical-align: middle;
        }
        table.data-table tr:nth-child(even) {
            background-color: #f8fafc;
        }

        /* Summary / Grand Total Row Styling */
        table.data-table tr.total-row td {
            background-color: #f1f5f9;
            font-weight: bold;
            color: #0f172a;
            border-top: 1.5px solid #cbd5e1;
            border-bottom: 1.5px solid #cbd5e1;
        }

        /* Badges */
        .badge {
            display: inline-block;
            padding: 1px 3px;
            font-size: 6px;
            font-weight: 700;
            text-transform: capitalize;
            border-radius: 2px;
            text-align: center;
        }
        .badge-borrowed { background-color: #e0e7ff; color: #3730a3; }
        .badge-returned { background-color: #d1fae5; color: #065f46; }
        .badge-overdue { background-color: #ffe4e6; color: #9f1239; }
        .badge-default { background-color: #f1f5f9; color: #334155; }

        .badge-cond-good { background-color: #ecfdf5; color: #047857; }
        .badge-cond-damaged { background-color: #fffbeb; color: #b45309; }
        .badge-cond-lost { background-color: #fff1f2; color: #be123c; }

        /* Status Colors */
        .text-danger { color: #dc2626; font-weight: bold; }
        .text-success { color: #16a34a; font-weight: bold; }

        /* Empty State */
        .empty-cell {
            text-align: center;
            color: #94a3b8;
            padding: 15px !important;
            font-style: italic;
        }
    </style>
</head>
<body>

    <!-- Header Section matching Acquisitions Report theme -->
    <div class="brand-title">BPS LIBRARY MANAGEMENT SYSTEM</div>
    <div class="brand-subtitle">Circulation Report</div>
    <hr class="header-divider">

    <!-- Meta Information Grid -->
    <div class="meta-card">
        <table class="meta-table">
            <tr>
                <td style="width: 50%;">
                    <span class="meta-label">Generated On:</span> {{ now()->format('F d, Y g:i A') }}<br>
                    <span class="meta-label">Search Filter:</span> {{ $search ?? 'None (All applied)' }}
                </td>
                <td style="width: 50%;">
                    <span class="meta-label">Total Records:</span> {{ count($activeLoans) }}<br>
                    <span class="meta-label">Generated By:</span> {{ auth()->user()?->getFullNameAttribute() ?? 'System Administrator' }}<br>
                    <span class="meta-label">Role:</span> {{ auth()->user()?->role ? ucwords(auth()->user()->role) : 'Librarian' }}
                </td>
            </tr>
        </table>
    </div>

    <!-- Data Table with Deep Blue Headers -->
    <table class="data-table">
        <thead>
            <tr>
                <th style="width: 7%;">Accession #</th>
                <th style="width: 13%;">Book Title</th>
                <th style="width: 8%;">ID #</th>
                <th style="width: 10%;">Name</th>
                <th style="width: 6%;">Type</th>
                <th style="width: 9%;">Borrowed Date</th>
                <th style="width: 7%;">Due Date</th>
                <th style="width: 7%;">Returned Date</th>
                <th style="width: 7%;">Receipt #</th>
                <th style="width: 7%;">Payment</th>
                <th style="width: 7%;">Fine Amount</th>
                <th style="width: 7%;">Condition</th>
                <th style="width: 6%;">Status</th>
                <th style="width: 6%;">Processed</th>
            </tr>
        </thead>
        <tbody>
            @php
                $totalFineSum = 0;
            @endphp
            @forelse ($activeLoans as $loan)
                @php
                    if (!($loan->is_paid === true)) {
                        $totalFineSum += (float) ($loan->fine_amount ?? 0);
                    }

                    $cond = strtolower($loan->condition ?? 'good');
                    $condBadge = match($cond) {
                        'good' => 'badge-cond-good',
                        'damaged' => 'badge-cond-damaged',
                        'lost' => 'badge-cond-lost',
                        default => 'badge-default',
                    };

                    $status = strtolower($loan->status ?? '');
                    $statusBadge = match($status) {
                        'borrowed' => 'badge-borrowed',
                        'returned' => 'badge-returned',
                        'overdue' => 'badge-overdue',
                        default => 'badge-default',
                    };

                    $borrowerName = trim(implode(' ', array_filter([
                        $loan->patron?->first_name,
                        $loan->patron?->middle_name,
                        $loan->patron?->last_name,
                        $loan->patron?->suffix,
                    ])));

                    $processedBy = method_exists($loan->user, 'getFullNameAttribute')
                        ? $loan->user?->getFullNameAttribute()
                        : ($loan->user?->name ?? 'System User');
                @endphp
                <tr>
                    <td><strong>{{ strtoupper($loan->accession?->accession_number) ?? 'N/A' }}</strong></td>
                    <td>{{ ucwords($loan->accession->catalog->title) ?? 'N/A' }}</td>
                    <td>{{ $loan->patron?->school_id ?? 'N/A' }}</td>
                    <td>{{ $borrowerName ? ucwords($borrowerName) : 'N/A' }}</td>
                    <td>{{ ucwords($loan->patron?->patronType?->name) ?? 'N/A' }}</td>
                    <td>{{ $loan->borrowed_at?->format('M d, Y h:i A') ?? '-' }}</td>
                    <td>{{ strtolower($loan->patron?->patronType?->name) === 'student' ? $loan->due_at?->format('M d, Y') : '-' }}</td>
                    <td>{{ $loan->returned_at?->format('M d, Y h:i A') ?? '-' }}</td>
                    <td>{{ $loan->receipt_number ?? '-' }}</td>
                    @if ($loan->returned_at)
                        @if ($loan->fine_amount > 0)
                            <td>{{ $loan->is_paid === true ? 'Paid' : 'Unpaid' }}</td>
                        @else
                            <td>-</td>
                        @endif

                        @if ($loan->fine_amount > 0)
                            <td>
                                <span class="text-danger">
                                    P{{ number_format((float) ($loan->fine_amount ?? 0), 2) }}
                                </span>
                            </td>
                        @else
                            <td>
                                <span class="text-success">
                                    P{{ number_format((float) ($loan->fine_amount ?? 0), 2) }}
                                </span>
                            </td>
                        @endif
                    @else
                        <td>-</td>
                        <td>
                            <span class="empty-cell">₱{{ number_format((float) ($loan->fine_amount ?? 0), 2) }}</span>
                        </td>
                    @endif
                    <td>
                        <span class="badge {{ $condBadge }}">{{ ucwords($loan->condition ?? 'Good') }}</span>
                    </td>
                    <td>
                        <span class="badge {{ $statusBadge }}">{{ ucwords($loan->status ?? 'N/A') }}</span>
                    </td>
                    <td>
                        {{ ucwords(strtolower($processedBy)) }}
                    </td>
                </tr>
            @empty
                <tr>
                    <td colspan="14" class="empty-cell">
                        No circulation records found matching criteria.
                    </td>
                </tr>
            @endforelse

            <!-- Grand Total Row -->
            @if(count($activeLoans) > 0)
                <tr class="total-row">
                    <td colspan="10" style="text-align: right; text-transform: uppercase;">Grand Total (Unpaid Fines):</td>
                    <td colspan="4">P{{ number_format($totalFineSum, 2) }}</td>
                </tr>
                <tr class="total-row">
                    <td colspan="10" style="text-align: right; text-transform: uppercase;">Grand Total (Paid Fines):</td>
                    <td colspan="4">P{{ number_format($totalPaidFineSum, 2) }}</td>
                </tr>
            @endif
        </tbody>
    </table>

</body>
</html>
