<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Inventory Summary Report</title>
    <style>
        body { font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; font-size: 9px; color: #1e293b; margin: 0; padding: 20px; }
        .header-title { font-size: 14px; font-weight: bold; color: #1e3a8a; text-transform: uppercase; margin-bottom: 2px; }
        .header-subtitle { font-size: 11px; font-weight: bold; color: #475569; margin-bottom: 10px; border-bottom: 2px solid #1e3a8a; padding-bottom: 6px; }

        .meta-box { background-color: #f8fafc; border: 1px solid #e2e8f0; padding: 8px 12px; margin-bottom: 12px; width: 100%; }
        .meta-table { width: 100%; border-collapse: collapse; }
        .meta-table td { font-size: 9px; color: #475569; padding: 2px 0; border: none; width: 50%; }

        /* Fixed Stats Card Grid Layout */
        .stats-table { width: 100%; border-collapse: collapse; margin-bottom: 15px; table-layout: fixed; }
        .stats-table td { padding: 0 4px; width: 20%; vertical-align: top; }
        .stats-table td:first-child { padding-left: 0; }
        .stats-table td:last-child { padding-right: 0; }

        .stat-card { background: #f8fafc; border: 1px solid #cbd5e1; border-radius: 4px; padding: 8px; text-align: left; }
        .stat-label { font-size: 7px; font-weight: bold; color: #64748b; text-transform: uppercase; margin-bottom: 4px; }
        .stat-value { font-size: 14px; font-weight: bold; color: #0f172a; }

        table.data-table { width: 100%; border-collapse: collapse; margin-top: 5px; }
        table.data-table th, table.data-table td { border: 1px solid #cbd5e1; padding: 6px 8px; text-align: left; }
        table.data-table th { background-color: #1e3a8a; color: #ffffff; font-weight: bold; font-size: 9px; text-transform: uppercase; }
        table.data-table td { font-size: 9px; }

        .text-center { text-align: center; }
        .footer { position: fixed; bottom: 0; left: 0; right: 0; font-size: 8px; color: #94a3b8; text-align: right; border-top: 1px solid #e2e8f0; padding-top: 5px; }
    </style>
</head>
<body>
    <div class="header-title">BPS Library Management System</div>
    <div class="header-subtitle">Inventory Summary Report</div>

    <div class="meta-box">
        <table class="meta-table">
            <tr>
                <td><strong>Generated On:</strong> {{ date('F d, Y h:i A') }}</td>
                <td><strong>Total Catalogs:</strong> {{ $catalogs->count() }}</td>
            </tr>
            <tr>
                <td><strong>Search Filter:</strong> {{ $search ?? 'None (All applied)' }}</td>
                <td><strong>Generated By:</strong> {{ method_exists(auth()->user(), 'getFullNameAttribute') ? auth()->user()->fullName : (auth()->user()->name ?? 'System User') }}</td>
            </tr>
            <tr>
                <td></td>
                <td><strong>Role:</strong> {{ ucwords(auth()->user()->role) ?? 'System User' }}</td>
            </tr>
        </table>
    </div>

    <!-- Properly Aligned Statistics Cards Table Grid -->
    <table class="stats-table">
        <tr>
            <td>
                <div class="stat-card">
                    <div class="stat-label">Total Physical Copies</div>
                    <div class="stat-value">{{ $stats['total_items'] }}</div>
                </div>
            </td>
            <td>
                <div class="stat-card">
                    <div class="stat-label">Available Copies</div>
                    <div class="stat-value" style="color: #059669;">{{ $stats['total_available'] }}</div>
                </div>
            </td>
            <td>
                <div class="stat-card">
                    <div class="stat-label">Currently on Loan</div>
                    <div class="stat-value" style="color: #7c3aed;">{{ $stats['total_on_loan'] }}</div>
                </div>
            </td>
            <td>
                <div class="stat-card">
                    <div class="stat-label">Damaged</div>
                    <div class="stat-value" style="color: #dc2626;">{{ $stats['total_damaged'] }}</div>
                </div>
            </td>
            <td>
                <div class="stat-card">
                    <div class="stat-label">Lost</div>
                    <div class="stat-value" style="color: #d97706;">{{ $stats['total_lost'] }}</div>
                </div>
            </td>
        </tr>
    </table>

    <table class="data-table">
        <thead>
            <tr>
                <th>Title</th>
                <th>ISBN</th>
                <th>Author</th>
                <th>Asset Type</th>
                <th class="text-center">Total</th>
                <th class="text-center">Available</th>
                <th class="text-center">On Loan</th>
                <th class="text-center">Reserved</th>
                <th class="text-center">Maint.</th>
                <th class="text-center">Damaged</th>
                <th class="text-center">Lost</th>
                <th class="text-center">Batches</th>
            </tr>
        </thead>
        <tbody>
            @forelse ($catalogs as $catalog)
                <tr>
                    <td>{{ ucwords($catalog->title) }}</td>
                    <td>{{ $catalog->isbn_issn ?? 'N/A' }}</td>
                    <td>{{ ucwords($catalog->author->name ?? 'Unknown') }}</td>
                    <td>{{ ucwords($catalog->assetType->name ?? 'Standard') }}</td>
                    <td class="text-center"><strong>{{ $catalog->total_copies }}</strong></td>
                    <td class="text-center">{{ $catalog->available_copies }}</td>
                    <td class="text-center">{{ $catalog->on_loan_copies }}</td>
                    <td class="text-center">{{ $catalog->reserved_copies }}</td>
                    <td class="text-center">{{ $catalog->maintenance_copies }}</td>
                    <td class="text-center">{{ $catalog->damaged_copies }}</td>
                    <td class="text-center">{{ $catalog->lost_copies }}</td>
                    <td class="text-center">{{ $catalog->acquisition_batches }}</td>
                </tr>
            @empty
                <tr>
                    <td colspan="12" class="text-center" style="padding: 20px; color: #94a3b8;">No records found.</td>
                </tr>
            @endforelse
        </tbody>
    </table>

    <div class="footer">
        Inventory Management System &bull; Page 1
    </div>
</body>
</html>
