<?php

namespace App\Exports;

use App\Models\Accession;
use Illuminate\Database\Eloquent\Builder as EloquentBuilder;
use Illuminate\Database\Eloquent\Relations\Relation;
use Illuminate\Database\Query\Builder;
use Illuminate\Support\Carbon;
use Maatwebsite\Excel\Concerns\FromQuery;
use Maatwebsite\Excel\Concerns\ShouldAutoSize;
use Maatwebsite\Excel\Concerns\WithCustomStartCell;
use Maatwebsite\Excel\Concerns\WithEvents;
use Maatwebsite\Excel\Concerns\WithHeadings;
use Maatwebsite\Excel\Concerns\WithMapping;
use Maatwebsite\Excel\Concerns\WithStyles;
use Maatwebsite\Excel\Events\BeforeSheet;
use PhpOffice\PhpSpreadsheet\Style\Fill;
use PhpOffice\PhpSpreadsheet\Worksheet\Worksheet;

class AccessionsExport implements FromQuery, WithHeadings, WithMapping, ShouldAutoSize, WithStyles, WithEvents, WithCustomStartCell
{
    protected string $search;
    protected string $statusFilter;

    public function __construct(string $search = '', string $statusFilter = '')
    {
        $this->search = trim($search);
        $this->statusFilter = trim($statusFilter);
    }

    public function startCell(): string
    {
        return 'A5'; // Data starts on row 5
    }

    public function query(): Builder|EloquentBuilder|Relation
    {
        $likeOperator = config('database.default') === 'pgsql' ? 'ilike' : 'like';

        return Accession::with([
            'catalog.author',
            'catalog.publisher',
            'catalog.assetType',
            'acquisition'
        ])
            ->when($this->search, function ($query) use ($likeOperator) {
                $query->where(function ($q) use ($likeOperator) {
                    $q->where('accession_number', $likeOperator, "%{$this->search}%")
                      ->orWhere('batch_number', $likeOperator, "%{$this->search}%")
                      ->orWhere('call_number', $likeOperator, "%{$this->search}%")
                      ->orWhereHas('catalog', fn ($sub) => $sub->where('title', $likeOperator, "%{$this->search}%"));
                });
            })
            ->when($this->statusFilter, fn ($q) => $q->where('status', $this->statusFilter))
            ->latest();
    }

    public function registerEvents(): array
    {
        return [
            BeforeSheet::class => function (BeforeSheet $event) {
                $sheet = $event->sheet->getDelegate();

                $userName = auth()->user()->getFullNameAttribute() ?? 'System';
                $searchLabel = !empty($this->search) ? $this->search : 'All (None applied)';
                $statusLabel = !empty($this->statusFilter) ? ucfirst($this->statusFilter) : 'All Statuses';

                $sheet->setCellValue('A1', 'BPS LIBRARY MANAGEMENT SYSTEM - ACCESSIONS REPORT');
                $sheet->setCellValue('A2', 'Generated On: ' . now()->format('F j, Y g:i A'));
                $sheet->setCellValue('E2', 'Generated By: ' . $userName);
                $sheet->setCellValue('A3', 'Search Query: ' . $searchLabel);
                $sheet->setCellValue('E3', 'Status Filter: ' . $statusLabel);

                $sheet->getStyle('A1')->getFont()->setBold(true)->setSize(14);
                $sheet->getStyle('A2:K3')->getFont()->setItalic(true)->setSize(10);
            },
        ];
    }

    public function headings(): array
    {
        return [
            'Accession #',
            'Batch #',
            'Acquisition #',
            'Catalog Title',
            'Author',
            'Publisher',
            'General Reference',
            'Asset Type',
            'Call Number',
            'Condition',
            'Status',
        ];
    }

    public function map($row): array
    {
        return [
            $row->accession_number,
            ucwords($row->batch_number),
            strtoupper($row->acquisition->acquisition_number),
            ucwords($row->catalog->title),
            ucwords($row->catalog->author->name),
            ucwords($row->catalog->publisher->name),
            ucwords($row->catalog->generalReference->name),
            ucwords($row->catalog->assetType->name),
            strtoupper($row->call_number),
            ucfirst($row->condition),
            ucfirst($row->status),
        ];
    }

    public function styles(Worksheet $sheet): array
    {
        return [
            5 => [
                'font' => ['bold' => true, 'color' => ['rgb' => 'FFFFFF']],
                'fill' => [
                    'fillType' => Fill::FILL_SOLID,
                    'startColor' => ['rgb' => '1E3A8A'],
                ],
            ],
        ];
    }
}
