<?php

namespace App\Exports;

use App\Models\Accession;
use Illuminate\Database\Eloquent\Builder as EloquentBuilder;
use Illuminate\Database\Eloquent\Relations\Relation;
use Illuminate\Database\Query\Builder;
use Maatwebsite\Excel\Concerns\FromQuery;
use Maatwebsite\Excel\Concerns\ShouldAutoSize;
use Maatwebsite\Excel\Concerns\WithCustomStartCell;
use Maatwebsite\Excel\Concerns\WithEvents;
use Maatwebsite\Excel\Concerns\WithHeadings;
use Maatwebsite\Excel\Concerns\WithMapping;
use Maatwebsite\Excel\Concerns\WithStyles;
use Maatwebsite\Excel\Events\BeforeSheet;
use PhpOffice\PhpSpreadsheet\Style\Fill;
use PhpOffice\PhpSpreadsheet\Worksheet\Worksheet;

class AccessionsExport implements FromQuery, WithHeadings, WithMapping, ShouldAutoSize, WithStyles, WithEvents, WithCustomStartCell
{
    protected string $search;
    protected string $statusFilter;

    public function __construct(string $search = '', string $statusFilter = '')
    {
        $this->search = trim($search);
        $this->statusFilter = trim($statusFilter);
    }

    public function startCell(): string
    {
        return 'A7';
    }

    public function query(): Builder|EloquentBuilder|Relation
    {
        $likeOperator = config('database.default') === 'pgsql' ? 'ilike' : 'like';

        return Accession::with([
            'catalog.author',
            'catalog.publisher',
            'catalog.generalReference',
            'catalog.assetType',
            'acquisition'
        ])
            ->when($this->search, function ($query) use ($likeOperator) {
                $query->where(function ($q) use ($likeOperator) {
                    $q->where('accession_number', $likeOperator, "%{$this->search}%")
                      ->orWhere('batch_number', $likeOperator, "%{$this->search}%")
                      ->orWhere('call_number', $likeOperator, "%{$this->search}%")
                      ->orWhereHas('catalog', fn ($sub) => $sub->where('title', $likeOperator, "%{$this->search}%"));
                });
            })
            ->when($this->statusFilter, fn ($q) => $q->where('status', $this->statusFilter))
            ->orderBy('accession_number', 'asc');
    }

    public function registerEvents(): array
    {
        return [
            BeforeSheet::class => function (BeforeSheet $event) {
                $sheet = $event->sheet->getDelegate();

                $userName = auth()->user()?->getFullNameAttribute() ?? 'System User';
                $roleName = ucfirst(auth()->user()?->role ?? 'Administrator');
                $searchLabel = !empty($this->search) ? '"' . $this->search . '"' : 'All (None applied)';
                $statusLabel = !empty($this->statusFilter) ? ucfirst($this->statusFilter) : 'All Statuses';

                $sheet->setCellValue('A1', 'BPS LIBRARY MANAGEMENT SYSTEM');
                $sheet->setCellValue('A2', 'Accessions Report');
                $sheet->setCellValue('A4', 'Generated On: ' . now()->format('F d, Y h:i A'));
                $sheet->setCellValue('E4', 'Generated By: ' . $userName);
                $sheet->setCellValue('A5', 'Search Filter: ' . $searchLabel);
                $sheet->setCellValue('E5', 'Status Filter: ' . $statusLabel);
                $sheet->setCellValue('E6', 'Role: ' . $roleName);

                $sheet->getStyle('A1')->getFont()->setBold(true)->setSize(13)->getColor()->setARGB('1E3A8A');
                $sheet->getStyle('A2')->getFont()->setBold(true)->setSize(11)->getColor()->setARGB('4B5563');
                $sheet->getStyle('A4:E6')->getFont()->setSize(9)->getColor()->setARGB('6B7280');
            },
        ];
    }

    public function headings(): array
    {
        return [
            'Accession #',
            'Batch #',
            'Acquisition #',
            'Title',
            'Author',
            'Publisher',
            'Gen. Ref',
            'Asset Type',
            'Call Number',
            'Condition',
            'Status',
        ];
    }

    public function map($row): array
    {
        return [
            strtoupper($row->accession_number),
            strtoupper($row->batch_number),
            strtoupper($row->acquisition->acquisition_number ?? '—'),
            ucwords($row->catalog->title ?? 'N/A'),
            ucwords($row->catalog->author->name ?? 'N/A'),
            ucwords($row->catalog->publisher->name ?? 'N/A'),
            ucwords($row->catalog->generalReference->name ?? 'N/A'),
            ucwords($row->catalog->assetType->name ?? 'N/A'),
            strtoupper($row->call_number ?? 'N/A'),
            ucfirst($row->condition ?? 'N/A'),
            ucfirst($row->status ?? 'N/A'),
        ];
    }

    public function styles(Worksheet $sheet): array
    {
        return [
            7 => [
                'font' => ['bold' => true, 'color' => ['argb' => 'FFFFFF']],
                'fill' => [
                    'fillType' => Fill::FILL_SOLID,
                    'startColor' => ['argb' => '1E3A8A'],
                ],
            ],
        ];
    }
}
