<?php

namespace App\Exports;

use App\Models\Acquisition;
use Illuminate\Database\Eloquent\Builder;
use Maatwebsite\Excel\Concerns\Exportable;
use Maatwebsite\Excel\Concerns\FromQuery;
use Maatwebsite\Excel\Concerns\ShouldAutoSize;
use Maatwebsite\Excel\Concerns\WithCustomStartCell;
use Maatwebsite\Excel\Concerns\WithEvents;
use Maatwebsite\Excel\Concerns\WithHeadings;
use Maatwebsite\Excel\Concerns\WithMapping;
use Maatwebsite\Excel\Events\AfterSheet;
use PhpOffice\PhpSpreadsheet\Style\Fill;
use PhpOffice\PhpSpreadsheet\Worksheet\Worksheet;

class AcquisitionsExport implements FromQuery, ShouldAutoSize, WithHeadings, WithMapping, WithCustomStartCell, WithEvents
{
    use Exportable;

    public function __construct(private readonly string $search = '')
    {
    }

    public function query(): Builder
    {
        $likeOperator = config('database.default') === 'pgsql' ? 'ilike' : 'like';
        $searchTerm = addcslashes(trim($this->search), '%_\\');

        return Acquisition::query()
            ->with(['catalog.author', 'catalog.assetType', 'vendor'])
            ->when($searchTerm !== '', function ($query) use ($likeOperator, $searchTerm) {
                $query->where(function ($q) use ($likeOperator, $searchTerm) {
                    $q->where('acquisition_number', $likeOperator, "%{$searchTerm}%")
                      ->orWhere('transaction_number', $likeOperator, "%{$searchTerm}%")
                      ->orWhereHas('catalog', fn ($sub) => $sub->where('title', $likeOperator, "%{$searchTerm}%"))
                      ->orWhereHas('vendor', fn ($sub) => $sub->where('company_name', $likeOperator, "%{$searchTerm}%"));
                });
            })
            ->latest();
    }

    public function startCell(): string
    {
        return 'A5';
    }

    public function headings(): array
    {
        return [
            'Acquisition No.',
            'Transaction No.',
            'Delivery Type',
            'Catalog Title',
            'Author',
            'Asset Type',
            'Vendor',
            'Quantity',
            'Unit Cost',
            'Total Cost',
            'Received Date',
            'Remarks',
        ];
    }

    public function map($acquisition): array
    {
        return [
            strtoupper($acquisition->acquisition_number),
            strtoupper($acquisition->transaction_number),
            ucwords($acquisition->delivery_type),
            ucwords($acquisition->catalog->title ?? 'N/A'),
            ucwords($acquisition->catalog->author->name ?? 'N/A'),
            ucwords($acquisition->catalog->assetType->name ?? 'N/A'),
            ucwords($acquisition->vendor->company_name ?? 'N/A'),
            $acquisition->quantity,
            (float) $acquisition->unit_cost,
            (float) $acquisition->total_cost,
            $acquisition->received_date ? $acquisition->received_date->format('Y-m-d') : '',
            ucfirst($acquisition->remarks) ?? '',
        ];
    }

    public function registerEvents(): array
    {
        return [
            AfterSheet::class => function (AfterSheet $event) {
                $sheet = $event->sheet->getDelegate();

                // Title Block matching PDF theme
                $sheet->setCellValue('A1', 'BPS LIBRARY MANAGEMENT SYSTEM');
                $sheet->getStyle('A1')->getFont()->setBold(true)->setSize(13)->getColor()->setARGB('1E3A8A');

                $sheet->setCellValue('A2', 'Acquisitions Report');
                $sheet->getStyle('A2')->getFont()->setBold(true)->setSize(11)->getColor()->setARGB('4B5563');

                // Metadata Block
                $sheet->setCellValue('A3', 'Generated On: ' . now()->format('F d, Y h:i A'));
                $sheet->setCellValue('F3', 'Generated By: ' . (auth()->user()->getFullNameAttribute() ?? 'System User'));
                $sheet->setCellValue('F4', 'Role: ' . (auth()->user()->role ?? 'Librarian'));
                $sheet->setCellValue('A4', 'Search Filter: ' . (!empty($this->search) ? '"' . $this->search . '"' : 'None (All applied)'));
                $sheet->getStyle('A3:F4')->getFont()->setSize(9)->getColor()->setARGB('6B7280');

                // Table Header Styling (Deep Blue background with bold white text)
                $sheet->getStyle('A5:K5')->applyFromArray([
                    'font' => [
                        'bold' => true,
                        'color' => ['argb' => 'FFFFFF'],
                    ],
                    'fill' => [
                        'fillType' => Fill::FILL_SOLID,
                        'startColor' => ['argb' => '1E3A8A'],
                    ],
                ]);
            },
        ];
    }
}
