<?php

namespace App\Exports;

use App\Models\PatronLog;
use Carbon\Carbon;
use Illuminate\Database\Eloquent\Builder as EloquentBuilder;
use Illuminate\Database\Eloquent\Relations\Relation;
use Illuminate\Database\Query\Builder;
use Maatwebsite\Excel\Concerns\FromQuery;
use Maatwebsite\Excel\Concerns\ShouldAutoSize;
use Maatwebsite\Excel\Concerns\WithCustomStartCell;
use Maatwebsite\Excel\Concerns\WithEvents;
use Maatwebsite\Excel\Concerns\WithHeadings;
use Maatwebsite\Excel\Concerns\WithMapping;
use Maatwebsite\Excel\Concerns\WithStyles;
use Maatwebsite\Excel\Events\AfterSheet;
use PhpOffice\PhpSpreadsheet\Worksheet\Worksheet;

class BorrowerLogsExport implements FromQuery, WithHeadings, WithMapping, ShouldAutoSize, WithCustomStartCell, WithStyles, WithEvents
{
    protected string $search;
    protected ?string $filterDate;
    protected string $filterStatus;
    protected string $generatedByName;
    protected string $generatedByRole;

    public function __construct(string $search = '', ?string $filterDate = null, string $filterStatus = 'all')
    {
        $this->search = trim(strip_tags($search));
        $this->filterDate = ! empty($filterDate) ? $filterDate : null;
        $this->filterStatus = $filterStatus;

        $user = auth()->user();
        $this->generatedByName = $user ? $user->getFullNameAttribute() : 'System Administrator';
        $this->generatedByRole = $user ? ($user->role ?? 'Staff') : 'Admin';
    }

    public function query(): Builder|EloquentBuilder|Relation
    {
        $likeOperator = config('database.default') === 'pgsql' ? 'ilike' : 'like';

        return PatronLog::with(['patron.patronType', 'patron.gradeLevel', 'patron.section'])
            ->when(! empty($this->filterDate), fn ($q) => $q->whereDate('log_date', $this->filterDate))
            ->when($this->filterStatus === 'inside', fn ($q) => $q->whereNull('time_out'))
            ->when($this->filterStatus === 'logged_out', fn ($q) => $q->whereNotNull('time_out'))
            ->when($this->search !== '', function ($query) use ($likeOperator) {
                $query->whereHas('patron', function ($q) use ($likeOperator) {
                    $q->where('school_id', $likeOperator, "%{$this->search}%")
                        ->orWhere('first_name', $likeOperator, "%{$this->search}%")
                        ->orWhere('middle_name', $likeOperator, "%{$this->search}%")
                        ->orWhere('last_name', $likeOperator, "%{$this->search}%");
                });
            })
            ->latest('id');
    }

    /**
     * Start data table from row 7 to leave room for metadata header rows.
     */
    public function startCell(): string
    {
        return 'A7';
    }

    public function headings(): array
    {
        return [
            'Log Date',
            'Student/Employee #',
            'Borrower Name',
            'Borrower Type',
            'Grade & Section',
            'Time In',
            'Time Out',
            'Status',
        ];
    }

    public function map($log): array
    {
        if ($log->patron) {
            $fullName = implode(' ', array_filter([
                $log->patron->first_name ?? '',
                $log->patron->middle_name ?? '',
                $log->patron->last_name ?? '',
                $log->patron->suffix ?? '',
            ]));
        } else {
            $fullName = 'Deleted Borrower';
        }

        $gradeSection = optional($log->patron)->gradeLevel
            ? (ucwords($log->patron->gradeLevel->name) . (optional($log->patron->section)->name ? ' - ' . ucwords($log->patron->section->name) : ''))
            : 'N/A';

        return [
            $log->log_date ? Carbon::parse($log->log_date)->format('M d, Y') : '',
            $log->patron->school_id ?? 'N/A',
            $fullName,
            $log->patron->patronType->name ?? 'N/A',
            $gradeSection,
            $log->time_in ? Carbon::parse($log->time_in)->format('h:i:s A') : '--:--:--',
            $log->time_out ? Carbon::parse($log->time_out)->format('h:i:s A') : '--:--:--',
            $log->time_out ? 'Logged Out' : 'Inside Library',
        ];
    }

    public function registerEvents(): array
    {
        return [
            AfterSheet::class => function (AfterSheet $event) {
                $sheet = $event->sheet->getDelegate();

                // Prepend Custom Metadata Header
                $systemName = config('app.name', 'LIBRARY MANAGEMENT SYSTEM');
                $dateText = $this->filterDate ? Carbon::parse($this->filterDate)->format('M d, Y') : 'All Dates (Unfiltered)';
                $statusText = ucfirst(str_replace('_', ' ', $this->filterStatus));
                $searchText = $this->search !== '' ? '"' . $this->search . '"' : 'None';

                $sheet->setCellValue('A1', strtoupper($systemName) . ' - ATTENDANCE LOGS REPORT');
                $sheet->setCellValue('A2', 'Generated By: ' . $this->generatedByName . ' (' . $this->generatedByRole . ')');
                $sheet->setCellValue('A3', 'Generated On: ' . now()->format('F d, Y h:i A'));
                $sheet->setCellValue('A4', 'Filter Date: ' . $dateText . ' | Status: ' . $statusText . ' | Search: ' . $searchText);
            },
        ];
    }

    public function styles(Worksheet $sheet): array
    {
        return [
            // Title formatting
            1 => ['font' => ['bold' => true, 'size' => 14, 'color' => ['argb' => '1E293B']]],
            // Metadata info styling
            2 => ['font' => ['italic' => true, 'size' => 10]],
            3 => ['font' => ['italic' => true, 'size' => 10]],
            4 => ['font' => ['bold' => true, 'size' => 10, 'color' => ['argb' => '2563EB']]],
            // Table Header Row
            7 => [
                'font' => ['bold' => true, 'color' => ['argb' => 'FF000000']], // Black color
                'fill' => [
                    'fillType' => \PhpOffice\PhpSpreadsheet\Style\Fill::FILL_SOLID,
                ],
                'borders' => [
                    'allBorders' => [
                        'borderStyle' => \PhpOffice\PhpSpreadsheet\Style\Border::BORDER_THIN,
                        'color' => ['argb' => 'FF000000'],
                    ],
                ],
            ],
        ];
    }
}
