<?php

namespace App\Livewire;

use App\Models\Catalog;
use App\Models\AssetType;
use App\Models\Accession;
use App\Models\Acquisition;
use Illuminate\Support\Facades\DB;
use Livewire\Attributes\Layout;
use Livewire\Attributes\Title;
use Livewire\Component;
use Livewire\WithPagination;
use Symfony\Component\HttpFoundation\StreamedResponse;

class InventoryManagement extends Component
{
    use WithPagination;

    public string $search = '';
    public string $assetTypeFilter = 'all';

    public function updatingSearch(): void { $this->resetPage(); }
    public function updatingAssetTypeFilter(): void { $this->resetPage(); }

    private function getInventoryQuery()
    {
        $likeOperator = config('database.default') === 'pgsql' ? 'ilike' : 'like';

        return Catalog::with(['author', 'assetType'])
            ->withCount([
                'accessions as total_copies',
                'accessions as available_copies' => fn ($q) => $q->where('status', 'available'),
                'accessions as on_loan_copies' => fn ($q) => $q->where('status', 'on loan'),
                'accessions as reserved_copies' => fn ($q) => $q->where('status', 'reserved'),
                'accessions as maintenance_copies' => fn ($q) => $q->where('status', 'under maintenance'),
                'accessions as damaged_copies' => fn ($q) => $q->where(fn ($sub) => $sub->where('condition', 'damaged')->orWhere('status', 'damaged')),
                'accessions as lost_copies' => fn ($q) => $q->where(fn ($sub) => $sub->whereIn('condition', ['lost', 'missing'])->orWhereIn('status', ['lost', 'missing'])),
                'accessions as dumped_copies' => fn ($q) => $q->where(fn ($sub) => $sub->where('condition', 'dumped')->orWhere('status', 'dumped')),
                'accessions as acquisition_batches' => fn ($q) => $q->select(DB::raw('count(distinct(acquisition_id))')),
            ])
            ->when($this->assetTypeFilter !== 'all', fn ($q) => $q->where('asset_type_id', $this->assetTypeFilter))
            ->when($this->search, function ($q) use ($likeOperator) {
                $q->where(function ($sub) use ($likeOperator) {
                    $sub->where('title', $likeOperator, "%{$this->search}%")
                        ->orWhere('isbn_issn', $likeOperator, "%{$this->search}%")
                        ->orWhereHas('author', fn ($a) => $a->where('name', $likeOperator, "%{$this->search}%"))
                        ->orWhereHas('accessions', fn ($acc) => $acc->where('call_number', $likeOperator, "%{$this->search}%")->orWhere('accession_number', $likeOperator, "%{$this->search}%"));
                });
            })
            ->latest();
    }

    private function getSystemStats()
    {
        return [
            'total_items'     => Accession::count(),
            'total_available' => Accession::where('status', 'available')->count(),
            'total_on_loan'   => Accession::where('status', 'on loan')->count(),
            'total_damaged'   => Accession::where(fn ($q) => $q->where('condition', 'damaged')->orWhere('status', 'damaged'))->count(),
            'total_lost'      => Accession::where(fn ($q) => $q->whereIn('condition', ['lost', 'missing'])->orWhereIn('status', ['lost', 'missing']))->count(),
            'total_dumped'    => Accession::where(fn ($q) => $q->where('condition', 'dumped')->orWhere('status', 'dumped'))->count(),
        ];
    }

    public function exportExcel(): StreamedResponse
    {
        $filename = 'inventory-summary-' . date('Y-m-d') . '.csv';

        $catalogs = $this->getInventoryQuery()->get();
        $stats = $this->getSystemStats();
        $searchFilterText = $this->search ? "Title/Author/ISBN: '{$this->search}'" : 'None (All applied)';
        $assetTypeText = $this->assetTypeFilter === 'all' ? 'All' : (AssetType::find($this->assetTypeFilter)->name ?? 'Unknown');

        return response()->stream(function() use ($catalogs, $stats, $searchFilterText, $assetTypeText) {
            $file = fopen('php://output', 'w');
            fprintf($file, chr(0xEF).chr(0xBB).chr(0xBF));

            fputcsv($file, ['BPS LIBRARY MANAGEMENT SYSTEM']);
            fputcsv($file, ['Inventory Summary Report']);
            fputcsv($file, ['Generated On: ' . date('F d, Y h:i A'), '', '', '', '', '', '', '', 'Generated By: ' . (auth()->user()->name ?? 'System User')]);
            fputcsv($file, ['Search Filter: ' . $searchFilterText, '', '', '', '', '', '', '', 'Asset Type Filter: ' . $assetTypeText]);
            fputcsv($file, []);

            fputcsv($file, ['OVERVIEW STATISTICS']);
            fputcsv($file, ['Total Physical Copies', 'Available Copies', 'Currently on Loan', 'Damaged Copies', 'Lost Copies', 'Dumped Copies']);
            fputcsv($file, [$stats['total_items'], $stats['total_available'], $stats['total_on_loan'], $stats['total_damaged'], $stats['total_lost'], $stats['total_dumped']]);
            fputcsv($file, []);

            fputcsv($file, ['Title', 'Author', 'Asset Type', 'Total', 'Available', 'On Loan', 'Reserved', 'Maintenance', 'Damaged', 'Lost', 'Dumped', 'Batches']);

            foreach ($catalogs as $catalog) {
                fputcsv($file, [
                    html_entity_decode(strip_tags($catalog->title . ($catalog->isbn_issn ? ' (ISBN: ' . $catalog->isbn_issn . ')' : ''))),
                    html_entity_decode(strip_tags($catalog->author->name ?? 'Unknown Author')),
                    html_entity_decode(strip_tags($catalog->assetType->name ?? 'Standard')),
                    $catalog->total_copies,
                    $catalog->available_copies,
                    $catalog->on_loan_copies,
                    $catalog->reserved_copies,
                    $catalog->maintenance_copies,
                    $catalog->damaged_copies,
                    $catalog->lost_copies,
                    $catalog->dumped_copies,
                    $catalog->acquisition_batches,
                ]);
            }
            fclose($file);
        }, 200, [
            "Content-type"        => "text/csv; charset=UTF-8",
            "Content-Disposition" => "attachment; filename={$filename}",
            "Pragma"              => "no-cache",
            "Cache-Control"       => "must-revalidate, post-check=0, pre-check=0",
            "Expires"             => "0"
        ]);
    }

    public function exportPdf()
    {
        $catalogs = $this->getInventoryQuery()->get();
        $stats = $this->getSystemStats();
        $searchFilterText = $this->search ? "Title/Author/ISBN: '{$this->search}'" : 'None (All applied)';

        $pdf = \Barryvdh\DomPDF\Facade\Pdf::loadView('pdf.inventory-summary', [
            'catalogs' => $catalogs,
            'stats'    => $stats,
            'search'   => $searchFilterText
        ])->setPaper('a4', 'landscape');

        $filename = 'inventory-summary-' . date('Y-m-d_H-i-s') . '.pdf';

        return response()->streamDownload(function () use ($pdf) {
            echo $pdf->output();
        }, $filename, [
            'Content-Type' => 'application/pdf',
        ]);
    }

    #[Layout('components.layouts.app')]
    #[Title('Inventory Summary')]
    public function render()
    {
        return view('livewire.inventory-management', [
            'catalogs'   => $this->getInventoryQuery()->paginate(15),
            'assetTypes' => AssetType::orderBy('name')->get(),
            'stats'      => $this->getSystemStats(),
        ]);
    }
}
